[package]
authors = ["Chorus One <techops@chorus.one>"]
description = "Solido Command-line Utility"
edition = "2018"
name = "solido-cli"
version = "0.1.0"

[dependencies]
bincode = "1.3.1"
borsh = "0.8"
bs58 = "0.4.0"
clap = "2.33.3"
lazy_static = "1.4.0"
lido = {path = "../program", features = ["no-entrypoint"]}
serde_json = "1.0.62"
solana-account-decoder = "1.6.6"
solana-clap-utils = "1.6.6"
solana-cli-config = "1.6.6"
solana-client = "1.6.6"
solana-logger = "1.6.6"
solana-program = "1.6.6"
solana-sdk = "1.6.6"
spl-stake-pool = {version = "*", features = ["no-entrypoint"]}
spl-token = {version = "*", features = ["no-entrypoint"]}

[[bin]]
name = "solido"
path = "src/main.rs"
